In [1]:
import numpy as np

In [2]:
a=np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[8]

9

In [5]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a[:-2]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a[1:5]=100

In [10]:
a

array([  1, 100, 100, 100, 100,   6,   7,   8,   9])

In [11]:
a[6:9]=90

In [12]:
a

array([  1, 100, 100, 100, 100,   6,  90,  90,  90])

In [13]:
z=a[4:]
z

array([100,   6,  90,  90,  90])

In [14]:
z[1:3]=70
z

array([100,  70,  70,  90,  90])

In [15]:
a

array([  1, 100, 100, 100, 100,  70,  70,  90,  90])

In [16]:
x=a.copy()
x

array([  1, 100, 100, 100, 100,  70,  70,  90,  90])

In [17]:
array=np.array(([1,2,3],[4,5,6],[7,8,9]))
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array[0]

array([1, 2, 3])

In [19]:
array[0,2]

3

In [20]:
array[:1,2:]

array([[3]])

In [21]:
array2d=np.zeros((10,5))
array2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
array2d.shape[1]

5

In [23]:
length=array2d.shape[1]
length

5

In [24]:
for i in range(length):
    array2d[i]=i
    
array2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
array2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
y=np.arange(1,11)

In [28]:
y > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
y[y>5]

array([ 6,  7,  8,  9, 10])