In [1]:
l=[1,2,3]
l

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(l)

array([1, 2, 3])

In [4]:
matrix=[[1,2,3,],[4,5,6],[7,8,9]]

In [5]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [14]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [15]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.34347145, 0.43452719, 0.30616494, 0.34200399, 0.67778709])

In [17]:
np.random.rand(6,7)

array([[0.08875736, 0.68912127, 0.21656145, 0.74236909, 0.46420539,
        0.45032721, 0.30952301],
       [0.49418493, 0.11739981, 0.31153271, 0.61592281, 0.58197333,
        0.34724594, 0.50921597],
       [0.59635293, 0.65534219, 0.35621559, 0.46502643, 0.12233509,
        0.86376929, 0.90792616],
       [0.13953897, 0.5033442 , 0.30381014, 0.3198281 , 0.85349095,
        0.62913587, 0.39532838],
       [0.11423732, 0.98476955, 0.49198971, 0.08630642, 0.71751314,
        0.53318731, 0.96995518],
       [0.46724674, 0.41680709, 0.40030785, 0.09220745, 0.67724928,
        0.04537216, 0.76928099]])

In [18]:
np.random.rand(4,6)

array([[0.45891433, 0.66655246, 0.56123208, 0.86559071, 0.26182783,
        0.52281745],
       [0.88530426, 0.86577589, 0.10133391, 0.64950043, 0.29094962,
        0.85793014],
       [0.61459132, 0.22921915, 0.70005371, 0.60143437, 0.30006111,
        0.53268376],
       [0.52694208, 0.35758961, 0.80874662, 0.1640354 , 0.03446895,
        0.10498935]])

In [19]:
np.random.randint(1,100)

25

In [20]:
np.random.randint(1,100,10)

array([16, 34,  3, 78, 52, 75, 87, 55,  1, 13])

In [21]:
arr=np.arange(0,10,3)

In [22]:
arr

array([0, 3, 6, 9])

In [23]:
rarr=np.random.randint(1,10,3)

In [24]:
rarr

array([8, 6, 1])

In [25]:
arr.reshape(2,2)

array([[0, 3],
       [6, 9]])

In [26]:
arr.max()

9

In [27]:
arr.min()

0

In [28]:
arr.argmin()

0

In [29]:
arr.argmax()

3

In [30]:
arr.shape

(4,)

In [31]:
arr.reshape(2,2)

array([[0, 3],
       [6, 9]])

In [32]:
arr.reshape(2,2).shape

(2, 2)

In [33]:
arr.dtype

dtype('int32')